# Generated by Django 6.0 on 2026-01-05 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                ("id_deck", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Deck name")),
                (
                    "alternative_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Alternative deck name"
                    ),
                ),
                (
                    "archetype",
                    models.CharField(max_length=30, verbose_name="Archetype"),
                ),
                (
                    "color_identity",
                    models.CharField(max_length=30, verbose_name="Color identity"),
                ),
                (
                    "colors_used",
                    models.CharField(max_length=50, verbose_name="Colors used"),
                ),
                (
                    "meta_percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Meta percentage",
                    ),
                ),
            ],
            options={
                "ordering": ("-meta_percentage",),
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id_seller", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Seller name"
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Real name"
                    ),
                ),
                ("country", models.CharField(max_length=80, verbose_name="Country")),
                (
                    "sales_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sales count",
                    ),
                ),
                (
                    "available_items",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Available items",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(max_length=60, verbose_name="Seller type"),
                ),
                ("rating", models.CharField(max_length=50, verbose_name="Rating")),
                (
                    "approval_very_good",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Very good approval %"
                    ),
                ),
                (
                    "approval_good",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Good approval %"
                    ),
                ),
                (
                    "approval_neutral",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Neutral approval %"
                    ),
                ),
                (
                    "approval_bad",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Bad approval %"
                    ),
                ),
                (
                    "shipping_days",
                    models.IntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Shipping days",
                    ),
                ),
                (
                    "on_vacation",
                    models.BooleanField(default=False, verbose_name="On vacation"),
                ),
                (
                    "street_address",
                    models.CharField(
                        max_length=300, null=True, verbose_name="Street address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Postal code"
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=100, null=True, verbose_name="City"),
                ),
            ],
            options={
                "ordering": ("-sales_count",),
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id_card", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Card name")),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Version (e.g., V.1, V.2)",
                    ),
                ),
                (
                    "rarity",
                    models.CharField(max_length=50, null=True, verbose_name="Rarity"),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Card number in Set"
                    ),
                ),
                ("set", models.CharField(max_length=100, verbose_name="Set")),
                (
                    "image_url",
                    models.URLField(
                        max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
                (
                    "available_items",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Available items",
                    ),
                ),
                (
                    "price_from",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price from",
                    ),
                ),
                (
                    "price_trend",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price trend",
                    ),
                ),
                (
                    "avg_30_days",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="30 days average",
                    ),
                ),
                (
                    "avg_7_days",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="7 days average",
                    ),
                ),
                (
                    "avg_1_day",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="1 day average",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "version", "set")},
            },
        ),
        migrations.CreateModel(
            name="DeckCard",
            fields=[
                ("id_deck_card", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Card quantity",
                    ),
                ),
                ("role", models.CharField(max_length=20, verbose_name="Role")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.card"
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.deck"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deck",
            name="member_cards",
            field=models.ManyToManyField(through="main.DeckCard", to="main.card"),
        ),
        migrations.CreateModel(
            name="SellerCard",
            fields=[
                ("id_seller_card", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Available inventory",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Unit price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "condition",
                    models.CharField(max_length=40, verbose_name="Condition"),
                ),
                ("language", models.CharField(max_length=40, verbose_name="Language")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.card"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.seller"
                    ),
                ),
            ],
            options={
                "ordering": ("price", "-quantity"),
            },
        ),
        migrations.AddField(
            model_name="seller",
            name="cards",
            field=models.ManyToManyField(
                related_name="sellers", through="main.SellerCard", to="main.card"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deck",
            unique_together={("name", "alternative_name")},
        ),
    ]
