# Generated by Django 6.0 on 2026-01-05 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "preferred_archetype",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Preferred archetype",
                    ),
                ),
                (
                    "preferred_colors",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Preferred colors",
                    ),
                ),
            ],
            options={
                "ordering": ("username",),
            },
        ),
        migrations.RemoveField(
            model_name="seller",
            name="on_vacation",
        ),
        migrations.CreateModel(
            name="DeckRating",
            fields=[
                ("id_rating", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating (0-5)",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="main.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="main.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-rating",),
                "unique_together": {("user", "deck")},
            },
        ),
    ]
